audit_header: false
title: "East Valley's Best Real Estate Training"
description: Keller Williams Realty East Valley, a top Real Estate Agency, shares their own internal real estate agent training for free. Their Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  # - title: Join Our Team
  #   url: http://www.joinkwev.com/apply
  # - title: Events
  #   url: #
  - title: Free Strategy Call
    url: /contact/
  - title: Free Newsletter
    url: /subscribe/

client:
  name: Keller Williams East Valley
  title:
  license_number:
  about_markdown: |
    Did you know…Keller Williams is now the largest franchise in world? KW was "Built by Agents, for Agents" and is still ran that way today. We are a privately owned company where Agents are partners in our business. KW's Agents ARE our Stakeholders. In 2015, Keller Williams was named the #1 Training Company worldwide through Training Magazine's Top 125 list in ALL industries.

    What makes our office different? We are committed to everything that we do! Established in 1999, KW East Valley embodies the KW Models and Systems and strives to provide an environment for Agents to thrive in. We are the #1 KW office in the Southwest Region, currently #1 in Market Share for Tempe, AZ and #1 in Listings for the entire East Valley. With a full leadership team, KW East Valley is dedicated to supporting our agents to make the best decisions and developing profitable and sustainable businesses.
  market: East Valley
  brand: Each Office is Independently Owned and Operated
  brokerage:
  address: '2077 East Warner Road, #110<br>Tempe, AZ 85284'
  phone: 480-839-6600
  phone_type:
  phone2:
  phone2_type:
  email: KWEVCareers@gmail.com
  url: http://www.joinkwev.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.png
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Keller Williams can take your business to new heights."
    CTA_link_text: "Private Consultation"
    CTA_url: http://www.joinkwev.com/apply

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/KWEastValley
  linkedin_url:
  youtube_url: https://www.youtube.com/channel/UC0o3qpQRdpWqvnHjSNw6-Bw
  twitter_url: http://www.twitter.com/KW_EastValley
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Keller Williams East Valley - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'the best real estate training, real estate training programs, real estate training near me, real estate jobs, real estate training videos, 	real estate training topics, real estate training free, real estate training for new agents, real estate training online'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
